# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\fernando\Documents\GitHub\napari-psf-simulator\src\napari_psf_simulator\PyFocus\src\PyFocus\user_interface\mask_selection\mask_selection2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MaskWindow(object):
    def setupUi(self, MaskWindow):
        MaskWindow.setObjectName("MaskWindow")
        MaskWindow.resize(331, 225)
        self.centralwidget = QtWidgets.QWidget(MaskWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 161, 16))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 120, 301, 16))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 181, 16))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 180, 141, 16))
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(120, 10, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 271, 16))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 160, 241, 16))
        self.label_5.setObjectName("label_5")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 50, 291, 21))
        self.textEdit.setObjectName("textEdit")
        MaskWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MaskWindow)
        self.statusbar.setObjectName("statusbar")
        MaskWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MaskWindow)
        QtCore.QMetaObject.connectSlotsByName(MaskWindow)

    def retranslateUi(self, MaskWindow):
        _translate = QtCore.QCoreApplication.translate
        MaskWindow.setWindowTitle(_translate("MaskWindow", "Define phase mask"))
        self.label_3.setText(_translate("MaskWindow", "Available parameters:"))
        self.label.setText(_translate("MaskWindow", "phi (azimutal coordinate, from 0 to 2pi)"))
        self.label_4.setText(_translate("MaskWindow", "w0 (gaussian beam radius, mm)"))
        self.label_6.setText(_translate("MaskWindow", "k (wavenumber, 1/mm)"))
        self.pushButton.setText(_translate("MaskWindow", "Define mask"))
        self.label_2.setText(_translate("MaskWindow", " rho (radial coordinate, from 0 to phase mask radius)"))
        self.label_5.setText(_translate("MaskWindow", "f (focal distance of objective lens, mm)"))
        self.textEdit.setHtml(_translate("MaskWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">np.exp(1j*phi)</p></body></html>"))
