# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'front_end.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(754, 651)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(200, 540, 75, 21))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 570, 75, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setEnabled(True)
        self.comboBox.setGeometry(QtCore.QRect(340, 370, 171, 21))
        self.comboBox.setEditable(False)
        self.comboBox.setDuplicatesEnabled(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 371, 131))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(110, 31, 41, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(80, 31, 21, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(90, 61, 16, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 61, 41, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 100, 71, 20))
        self.label_3.setObjectName("label_3")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(9, 85, 100, 20))
        self.label_17.setObjectName("label_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_18.setGeometry(QtCore.QRect(110, 91, 41, 20))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_15.setGeometry(QtCore.QRect(320, 60, 41, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(175, 80, 141, 41))
        self.label_14.setObjectName("label_14")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(320, 30, 41, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(180, 50, 141, 41))
        self.label_10.setObjectName("label_10")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(172, 30, 151, 20))
        self.label_5.setObjectName("label_5")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_16.setGeometry(QtCore.QRect(320, 90, 41, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 430, 101, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_14.setGeometry(QtCore.QRect(100, 500, 171, 21))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 500, 81, 21))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(370, 430, 101, 40))
        self.pushButton_6.setObjectName("pushButton_6")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_21.setGeometry(QtCore.QRect(340, 400, 161, 19))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(200, 600, 75, 21))
        self.pushButton_4.setObjectName("pushButton_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 200, 271, 141))
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton.setGeometry(QtCore.QRect(20, 30, 291, 21))
        self.radioButton.setObjectName("radioButton")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_22.setEnabled(False)
        self.lineEdit_22.setGeometry(QtCore.QRect(220, 80, 41, 20))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setGeometry(QtCore.QRect(80, 80, 121, 16))
        self.label_23.setObjectName("label_23")
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(40, 50, 191, 16))
        self.label_11.setObjectName("label_11")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_19.setEnabled(False)
        self.lineEdit_19.setGeometry(QtCore.QRect(220, 110, 41, 20))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(30, 310, 191, 21))
        self.label_18.setObjectName("label_18")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(320, 200, 421, 141))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_20 = QtWidgets.QLabel(self.groupBox_5)
        self.label_20.setGeometry(QtCore.QRect(10, 45, 401, 21))
        self.label_20.setObjectName("label_20")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_23.setEnabled(False)
        self.lineEdit_23.setGeometry(QtCore.QRect(10, 65, 391, 20))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.label_25 = QtWidgets.QLabel(self.groupBox_5)
        self.label_25.setGeometry(QtCore.QRect(10, 89, 421, 21))
        self.label_25.setObjectName("label_25")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_24.setEnabled(False)
        self.lineEdit_24.setGeometry(QtCore.QRect(10, 109, 391, 20))
        self.lineEdit_24.setText("")
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 23, 141, 21))
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_26 = QtWidgets.QLabel(self.groupBox_5)
        self.label_26.setGeometry(QtCore.QRect(170, 25, 231, 16))
        self.label_26.setObjectName("label_26")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_25.setEnabled(False)
        self.lineEdit_25.setGeometry(QtCore.QRect(360, 23, 41, 20))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(580, 10, 161, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(104, 61, 41, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(20, 61, 81, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(104, 31, 41, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(14, 31, 91, 20))
        self.label_4.setObjectName("label_4")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(30, 91, 71, 16))
        self.label_16.setObjectName("label_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_17.setGeometry(QtCore.QRect(104, 91, 41, 20))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_20.setGeometry(QtCore.QRect(104, 121, 41, 20))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(30, 121, 71, 16))
        self.label_19.setObjectName("label_19")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_12.setGeometry(QtCore.QRect(104, 151, 41, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(60, 151, 21, 20))
        self.label_13.setObjectName("label_13")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(401, 40, 161, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_11.setGeometry(QtCore.QRect(110, 60, 41, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_13.setGeometry(QtCore.QRect(110, 30, 41, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(10, 60, 91, 20))
        self.label_9.setObjectName("label_9")
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setGeometry(QtCore.QRect(10, 30, 91, 21))
        self.label_24.setObjectName("label_24")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(250, 370, 81, 20))
        self.label_12.setObjectName("label_12")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(240, 400, 91, 16))
        self.label_15.setObjectName("label_15")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(10, 540, 171, 21))
        self.label_22.setObjectName("label_22")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(10, 570, 191, 21))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(10, 600, 171, 21))
        self.label_28.setObjectName("label_28")
        self.groupBox.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.comboBox.raise_()
        self.pushButton_3.raise_()
        self.lineEdit_14.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.lineEdit_21.raise_()
        self.pushButton_4.raise_()
        self.groupBox_4.raise_()
        self.label_18.raise_()
        self.groupBox_5.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.label_12.raise_()
        self.label_15.raise_()
        self.label_22.raise_()
        self.label_27.raise_()
        self.label_28.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyFocus"))
        self.pushButton.setText(_translate("MainWindow", "Save"))
        self.pushButton_2.setText(_translate("MainWindow", "Save"))
        self.comboBox.setItemText(0, _translate("MainWindow", "VP (Vortical 0-2pi)"))
        self.comboBox.setItemText(1, _translate("MainWindow", "No mask (Gaussian beam)"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Custom"))
        self.groupBox.setTitle(_translate("MainWindow", "Optical system"))
        self.lineEdit.setText(_translate("MainWindow", "1.4"))
        self.label.setText(_translate("MainWindow", "NA"))
        self.label_2.setText(_translate("MainWindow", "n"))
        self.lineEdit_2.setText(_translate("MainWindow", "1.5"))
        self.label_3.setText(_translate("MainWindow", "radius (mm)"))
        self.label_17.setText(_translate("MainWindow", "Objective aperture"))
        self.lineEdit_18.setText(_translate("MainWindow", "3"))
        self.lineEdit_15.setText(_translate("MainWindow", "1"))
        self.label_14.setText(_translate("MainWindow", "Gaussian beam radius (mm)"))
        self.lineEdit_3.setText(_translate("MainWindow", "640"))
        self.label_10.setText(_translate("MainWindow", "Laser intensity (mW/cm^2)"))
        self.label_5.setText(_translate("MainWindow", "Wavelength at vacuum (nm)"))
        self.lineEdit_16.setText(_translate("MainWindow", "5"))
        self.pushButton_3.setText(_translate("MainWindow", "Simulate"))
        self.lineEdit_14.setText(_translate("MainWindow", "(leave like this for local folder)"))
        self.pushButton_5.setText(_translate("MainWindow", "Saving folder"))
        self.pushButton_6.setText(_translate("MainWindow", "Clear images"))
        self.lineEdit_21.setText(_translate("MainWindow", "VP mask simulation"))
        self.pushButton_4.setText(_translate("MainWindow", "Save"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Field propagation"))
        self.radioButton.setText(_translate("MainWindow", "Simulate field propagation between "))
        self.lineEdit_22.setText(_translate("MainWindow", "5"))
        self.label_23.setText(_translate("MainWindow", "Phase mask radius (mm)"))
        self.label_11.setText(_translate("MainWindow", "phase mask and objective"))
        self.lineEdit_19.setText(_translate("MainWindow", "1000"))
        self.label_18.setText(_translate("MainWindow", "Phase mask - objective distance (mm)"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Multilayer system"))
        self.label_20.setText(_translate("MainWindow", "Refraction indices: n1,n2,...,ni with n1 the first medium and ni the last medium"))
        self.lineEdit_23.setText(_translate("MainWindow", "1.5,1.33"))
        self.label_25.setText(_translate("MainWindow", "Layer thicknesses: d2,...,di-1 in nm, first and last are semi-infinite"))
        self.radioButton_2.setText(_translate("MainWindow", "Simulate a multilayer"))
        self.label_26.setText(_translate("MainWindow", "Axial position of the multilayer (nm)"))
        self.lineEdit_25.setText(_translate("MainWindow", "0"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Range and resolution (nm)"))
        self.lineEdit_4.setText(_translate("MainWindow", "80"))
        self.label_6.setText(_translate("MainWindow", "Axial resolution"))
        self.lineEdit_5.setText(_translate("MainWindow", "30"))
        self.label_4.setText(_translate("MainWindow", "Radial resolution "))
        self.label_16.setText(_translate("MainWindow", "Radial range"))
        self.lineEdit_17.setText(_translate("MainWindow", "1000"))
        self.lineEdit_20.setText(_translate("MainWindow", "2000"))
        self.label_19.setText(_translate("MainWindow", "Axial range"))
        self.lineEdit_12.setText(_translate("MainWindow", "0"))
        self.label_13.setText(_translate("MainWindow", "z"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Polarization"))
        self.lineEdit_11.setText(_translate("MainWindow", "45"))
        self.lineEdit_13.setText(_translate("MainWindow", "90"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p>Gamma (degrees)</p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "Beta (degrees)"))
        self.label_12.setText(_translate("MainWindow", "Phase mask:"))
        self.label_15.setText(_translate("MainWindow", "Simulation name:"))
        self.label_22.setText(_translate("MainWindow", "Save text with used parameters:"))
        self.label_27.setText(_translate("MainWindow", "Save intensity on XZ and XY planes:"))
        self.label_28.setText(_translate("MainWindow", "Save amplitudes on the XY plane:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

